// Package frameworkbundle ships library source for projects generated by a standalone CLI.
package frameworkbundle

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

//go:embed framework.zip
var source []byte

// Extract writes the bundled library into a new directory owned by the generated
// project, so neither the original checkout nor a public module release is needed.
func Extract(directory string) error {
	archive, err := zip.NewReader(bytes.NewReader(source), int64(len(source)))
	if err != nil {
		return err
	}
	if err := os.Mkdir(directory, 0755); err != nil {
		return err
	}
	for _, file := range archive.File {
		path, err := filepath.Localize(file.Name)
		if err != nil {
			return fmt.Errorf("invalid bundled path %q: %w", file.Name, err)
		}
		target := filepath.Join(directory, path)
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			return err
		}
		input, err := file.Open()
		if err != nil {
			return err
		}
		output, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
		if err != nil {
			input.Close()
			return err
		}
		_, copyErr := io.Copy(output, input)
		input.Close()
		closeErr := output.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	return nil
}

// Cache extracts this exact embedded framework once into the user's cache and
// returns the stable directory for Go and editor tooling to reference.
func Cache() (string, error) {
	base, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(source)
	id := hex.EncodeToString(sum[:8])
	parent := filepath.Join(base, "Graft", "framework")
	target := filepath.Join(parent, id)
	if _, err := os.Stat(filepath.Join(target, "go.mod")); err == nil {
		return target, nil
	} else if !os.IsNotExist(err) {
		return "", err
	}
	if err := os.MkdirAll(parent, 0755); err != nil {
		return "", err
	}
	temporary, err := os.MkdirTemp(parent, ".extract-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(temporary)
	staged := filepath.Join(temporary, "framework")
	if err := Extract(staged); err != nil {
		return "", err
	}
	if err := os.Rename(staged, target); err != nil {
		if _, statErr := os.Stat(filepath.Join(target, "go.mod")); statErr == nil {
			return target, nil
		}
		return "", err
	}
	return target, nil
}

// PrepareModule extracts the embedded framework to a temporary directory and
// returns an alternate go.mod that replaces the framework dependency with it.
// The caller must invoke the returned cleanup function after Go finishes.
func PrepareModule(projectMod string) (modFile string, cleanup func(), err error) {
	data, err := os.ReadFile(projectMod)
	if err != nil {
		return "", nil, err
	}
	dir, err := os.MkdirTemp("", "graft-framework-*")
	if err != nil {
		return "", nil, err
	}
	cleanup = func() { _ = os.RemoveAll(dir) }
	framework := filepath.Join(dir, "framework")
	if err := Extract(framework); err != nil {
		cleanup()
		return "", nil, err
	}
	modFile = filepath.Join(dir, "graft.mod")
	replace := "\nreplace github.com/spidermeaow/graft-framework => " + filepath.ToSlash(framework) + "\n"
	if err := os.WriteFile(modFile, append(data, []byte(replace)...), 0600); err != nil {
		cleanup()
		return "", nil, err
	}
	if sum, readErr := os.ReadFile(filepath.Join(filepath.Dir(projectMod), "go.sum")); readErr == nil {
		if err := os.WriteFile(strings.TrimSuffix(modFile, ".mod")+".sum", sum, 0600); err != nil {
			cleanup()
			return "", nil, err
		}
	}
	return modFile, cleanup, nil
}
